project:
  type: website
  output-dir: docs

website:
  title: "Junkil Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme: litera
    toc: false
    css: styles.css