# Full Publications

First/Co-First author marked as *

15\. Choi, J., Kim, S., **Park, J.**, Choi, J., An, S., and Jung, Y. Next-Generation AI for Accelerated Materials Discovery. (submitted)

14\. Kim, S., Choi, J., Jang, K., **Park, J.**, Bernales, V., Aspuru-Guzik, A., and Jung, Y. Materealize: a multi-agent deliberation system for end-to-end material design and synthesis. (submitted)

13\. **Park, J.\***, Choi, J., and Jung, Y. Learning electrons to generate materials. Nature Communications 2026 (accepted)

12\. **Park, J.\***, Lee, Y., and Kim, J. Multi-modal conditional diffusion model using signed distance functions for metal-organic framework generation. Nature Communications 2025 16:34

11\. **Park, J.\***, Lee, W., and Kim, J. Large-Scale Construction and Analysis of Amorphous Porous Polymer Network Materials. ACS Appl. Mater. Interfaces 2024, 16, 57190-57199

10\. **Park, J.\***, Kim, H., Kang, Y., Lim, Y., and Kim, J. From Data to Discovery: Recent Trends of Machine Learning in Metal-Organic Frameworks. JACS Au 2024, 4, 3727-3743

9\. Hyun, T., **Park, J.\***,  So, J., Kim, J., and Koh, D, Unexpected molecular sieving of xylene isomers in polymer-metal-organic frameworks (PolyMOF) materials. Advanced Science 2024, 11, 2402980

8\. **Park, J.\***, Gill,APS., Moosavi,SM., and Kim. J, Inverse design of porous materials: a diffusion model approach. Journal of Materials Chemistry A 2024, 12, 6507-6514

7\. Ko,Y., **Park, J.**, Zhang, X., Kang, L., Pham T., Boureau V., Pham-Huu, C., Kim, J., Zhong, L., and Zuttel.  All platinum group metal-free catalyts using in liquid fuel operated direct borohydride fuel cells. ACS Appl. Energy Mater 2024, 7, 2, 639-648

6\. Lee, J., Lim,H., **Park, J.\***, Kim, M., Jung, J., Kim, J., and Kim, I. Flouring-Rich Oragnic Framework to Boost Electrochemicl Kinetics and Storages of K+ Ions for Potassium-Ion Battery. Advanced Energy Materials, 2023,13, 2300442

5\. **Park, J. \***, Lim, Y., Lee, S., and Kim, J. Computational Design of Metal-Organic Frameworks with Unprecedented High Hydrogen Working Capacity and High Synthesizability. Chemistry of Materials 2023, 35, 1, 9-16

4\. Dodson, RA., **Park, J.**, Kim, J., Cliffe, MJ., and Cohen, SM. Tehthering Effects in Oligomer-Based Metal-Organic Frameworks. Inorganic Chemistry 2022, 61, 31, 12284-12292

3\. Lim, Y., **Park, J.**, Lee, S., and Kim, J. Finely tuned inverse design of metal-organic frameworks with user-desired Xe/Kr selectivity. Journal of Materials Chemistry A 2021, 9, 21175-21183

2\. Sarango-Ramirez, MK., **Park, J.**, Kim, J., Yoshida, Y., Lim, DW., and Kitagawa, H. Void Space versus Surface Functionalization for Proton Conduction in Metal-Organic Frameworks. Angew. Chem. Int. Ed. 2021, 60, 20173-20177

1\. **Park, J.\***, Suh, BL., and Kim, J. Computational design of a photoresponsive metal-organic framework for post combustion carbon capture. J. Phys. Chem. C 2020, 124, 24, 13162-13167